### ISSUE TITLE
[Bug] DashChat is incompatible to Flutter v2.0.0

### ISSUE THREAD

**Issue by LostInDarkMath** [fayeed/dash_chat#163]
**Describe the bug**
I upgraded to Flutter v2.0.0 and after that I get a version solving problem, since `flutter_localizations` depends on `intl` 1.7.0, which is currently not supported by dash_chat.

**To Reproduce**
1. Install Flutter 2.0.0
2. Create a project with at least this depencies:
   ```yaml
   dependencies:
     flutter:
       sdk: flutter
     flutter_localizations: 
       sdk: flutter

     intl: ^0.17.0 
     dash_chat: ^1.1.15  
   ```
2. Run `flutter pub get`
3. See error
```
Because dash_chat >=1.0.10 depends on intl ^0.16.0 and foo depends on intl ^0.17.0, dash_chat >=1.0.10 is forbidden.
So, because foo depends on dash_chat ^1.1.15, version solving failed.
Running "flutter pub get" in foo...                              
pub get failed (1; So, because foo depends on dash_chat ^1.1.15, version solving failed.)
```

If I set `intl` to 1.16.0, which is supported by dash_chat, I get this error:
```
Because foo depends on flutter_localizations any from sdk which depends on intl 0.17.0, intl 0.17.0 is required.
So, because foodepends on intl ^0.16.1, version solving failed. 
Running "flutter pub get" in foo...                              
pub get failed (1; So, because foo depends on intl ^0.16.1, version solving failed.)
```

**Expected behavior**
No version solving Problems with `flutter pub get`.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Flutter Version: 2.0.0
 - Dart Version: 2.1.12
 - Dash Chat Version: 1.1.15
